- name: Install and Configure MariaDB
  hosts: all
  become: yes
  tasks:
  - name: Install unzip
    apt:
      name: unzip
      state: present
      update_cache: yes

  - name: Install MariaDB
    apt:
      name: 
        - mariadb-server
        - mariadb-client
      state: present
      update_cache: yes

  - name: Start and enable MariaDB service
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: true